version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: quizuser
      POSTGRES_PASSWORD: quizpasswd
      POSTGRES_DB: quizdb
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - quiz-network

networks:
  quiz-network:
    driver: bridge

volumes:
  quiz-volume:
    driver: local

